trigger:
- master

jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'
  strategy:
    matrix:
      Python27:
        python.version: '2.7'
        pytest.options: ''
        pip.command: 'pip install -e .[all,test]'
      Python36:
        python.version: '3.6'
        pytest.options: ''
        pip.command: 'pip install -e .[all,test]'
      Python37_RemoteData:
        python.version: '3.7'
        pytest.options: '--remote-data'
        pip.command: 'pip install -e .[all,test]'
      Python37_NoOptionalDependencies:
        python.version: '3.7'
        pytest.options: ''
        pip.command: 'pip install -e .[test]'

  steps:
  - template: .azure-template.yml

- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  strategy:
    matrix:
      Python37:
        python.version: '3.7'
        pytest.options: ''
        pip.command: 'pip install -e .[all,test]'
  steps:
  - template: .azure-template.yml
