trigger:
- master

jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - template: azure-steps.yml

- job: macOS
  pool:
    vmImage: 'macOS-10.13'
  steps:
  - template: azure-steps.yml

- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - template: azure-steps.yml