trigger:
- master

jobs:
- job: Test on Linux
  pool:
    vmImage: 'ubuntu-16.04'
  strategy:
    matrix:
      Python27:
        python.version: '2.7'
      Python36:
        python.version: '3.6'
      Python37:
        python.version: '3.7'
  steps:
  - template: azure-steps.yml

- job: Test on Windows
  pool:
    vmImage: 'vs2017-win2016'
  strategy:
    matrix:
      Python37:
        python.version: '3.7'
  steps:
  - template: azure-steps.yml
