trigger:
- master

jobs:
- job: LinuxTest
  pool:
    vmImage: 'ubuntu-16.04'
  strategy:
    matrix:
      Python27:
        python.version: '2.7'
        pytest.options: ''
      Python38:
        python.version: '3.8'
        pytest.options: ''
      Python37_RemoteData:
        python.version: '3.7'
        pytest.options: '--remote-data'
  steps:
  - template: azure-steps.yml

- job: WindowsTest
  pool:
    vmImage: 'vs2017-win2016'
  strategy:
    matrix:
      Python37:
        python.version: '3.7'
        pytest.options: ''
  steps:
  - template: azure-steps.yml
