trigger:
- master

jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'
  strategy:
    matrix:
      Python27:
        python.version: '2.7'
      Python36:
        python.version: '3.6'
      Python37:
        python.version: '3.7'
  steps:
  - template: azure-steps.yml

- job: macOS
  pool:
    vmImage: 'macOS-10.13'
  strategy:
    matrix:
      Python37:
        python.version: '3.7'
  steps:
  - template: azure-steps.yml

- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  strategy:
    matrix:
      Python37:
        python.version: '3.7'
  steps:
  - template: azure-steps.yml
