trigger:
- master

strategy:
  matrix:
    Linux:
      imageName: 'Ubuntu-16.04'
    Windows:
      imageName: 'vs2017-win2016'
    Python27:
      python.version: '2.7'
    Python36:
      python.version: '3.6'
    Python37:
      python.version: '3.7'

pool:
  vmImage: $(imageName)

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    python -m pip install --upgrade pip
    pip install numpy  # celerite needs numpy to build, so we install it first
    pip install -e .[all,test]
  displayName: 'Install Lightkurve & dependencies'

- script: |
    pytest
  displayName: 'pytest'
