
name: lightkurve
channels:
    - conda-forge
dependencies:
    - python
    - astropy >=1.3
    - astroquery >=0.3.9
    - beautifulsoup4
    - matplotlib >=1.5.3
    - numpy >=1.11
    - oktopus
    - pandas
    - bokeh >=1.0
    - requests
    - scipy >=0.19.0
    - tqdm
    - scikit-learn
    - pybind11
    - celerite
