#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# lightkurve documentation build configuration file, created by
# sphinx-quickstart on Thu May 11 16:52:07 2017.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import os
import sys
sys.path.append(os.path.join(os.path.dirname(__name__), '..'))

import lightkurve

# -- General configuration ------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.mathjax',
    'nbsphinx',
    'numpydoc',
    'sphinx_automodapi.automodapi']

numpydoc_show_class_members = False


# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# Exclude build directory and Jupyter backup files:
exclude_patterns = ['_build', '**.ipynb_checkpoints']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_suffix = '.rst'

# The master toctree document.
master_doc = 'index'

# General information about the project.
project = 'lightkurve'
copyright = 'lightkurve developers and contributors'
author = 'Kepler/K2 Guest Observer Office'

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
version = lightkurve.__version__.split('.dev')[0]
# The full version, including alpha/beta/rc tags.
release = lightkurve.__version__

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = None

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This patterns also effect to html_static_path and html_extra_path
exclude_patterns = []

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = True

# Some notebook cells take longer than 60 seconds to execute
nbsphinx_timeout = 300

# PUT PROLOG HERE
nbsphinx_prolog = r"""
{% set docname = env.doc2path(env.docname, base=None) %}

.. only:: html

    .. role:: raw-html(raw)
        :format: html

    .. nbinfo::
        **This tutorial is a static-text version of an interactive Jupyter notebook**

        - Try the interactive version: :raw-html:`<a href="https://mybinder.org/v2/gh/KeplerGO/lightkurve/master?filepath=docs/source/{{ docname }}"><img alt="Binder badge" src="https://mybinder.org/badge_logo.svg" style="vertical-align:text-bottom"></a>`

        - Download the source file: `{{ docname }}`__

    __ https://github.com/KeplerGO/lightkurve/blob/master/docs/source/
        {{ docname }}

"""

# This is processed by Jinja2 and inserted after each notebook
#nbsphinx_epilog = r""" text here """

# -- Options for HTML output ----------------------------------------------
html_theme = 'kurvian'
html_theme_path = ['../']

html_theme_options = {
    "navbar_title": "Lightkurve v" + version,
    "navbar_links": [
        ("Quickstart", "quickstart"),
        ("API", "api"),
        ("Tutorials", "tutorials/index"),
        ("About", "about"),
    ],
}

html_title = "Test 1 2 3"

html_static_path = ['_static']

html_logo = '_static/images/lightkurve.png'

sys.path += ['exts']
extensions += ['sphinxcontrib_rawfiles']
rawfiles = ['CNAME']  # Files we want to copy
